
package com.site.webService.call;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-07-04T10:42:09.354+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class TestWebServiceImpl_TestWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webService.site.com/", "TestWebServiceImplService");

    private TestWebServiceImpl_TestWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = TestWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TestWebServiceImplService ss = new TestWebServiceImplService(wsdlURL, SERVICE_NAME);
        TestWebServiceImpl port = ss.getTestWebServiceImplPort();  
        
        {
        System.out.println("Invoking showName...");
        String _showName_arg0 = "";
        String _showName__return = port.showName(_showName_arg0);
        System.out.println("showName.result=" + _showName__return);


        }
        {
        System.out.println("Invoking showInfo...");
        String _showInfo_arg0 = "";
        String _showInfo__return = port.showInfo(_showInfo_arg0);
        System.out.println("showInfo.result=" + _showInfo__return);


        }

        System.exit(0);
    }

}
