package com.site.webService.call;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-07-04T10:42:09.618+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "TestWebServiceImplService", 
                  wsdlLocation = "http://localhost:8180/mposBaseWeb/service/testWebServiceImpl?wsdl",
                  targetNamespace = "http://impl.webService.site.com/") 
public class TestWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webService.site.com/", "TestWebServiceImplService");
    public final static QName TestWebServiceImplPort = new QName("http://impl.webService.site.com/", "TestWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8180/mposBaseWeb/service/testWebServiceImpl?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8180/mposBaseWeb/service/testWebServiceImpl?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TestWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TestWebServiceImpl
     */
    @WebEndpoint(name = "TestWebServiceImplPort")
    public TestWebServiceImpl getTestWebServiceImplPort() {
        return super.getPort(TestWebServiceImplPort, TestWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebServiceImpl
     */
    @WebEndpoint(name = "TestWebServiceImplPort")
    public TestWebServiceImpl getTestWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TestWebServiceImplPort, TestWebServiceImpl.class, features);
    }

}
