package com.site.webService.call;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-07-04T10:42:09.597+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://impl.webService.site.com/", name = "TestWebServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface TestWebServiceImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "showName", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.ShowName")
    @WebMethod
    @ResponseWrapper(localName = "showNameResponse", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.ShowNameResponse")
    public String showName(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "showInfo", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.ShowInfo")
    @WebMethod
    @ResponseWrapper(localName = "showInfoResponse", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.ShowInfoResponse")
    public String showInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
