package com.site.webService.call;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-09-13T16:55:50.715+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://impl.webService.site.com/", name = "PosWebServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface PosWebServiceImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPromName", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.QueryPromName")
    @WebMethod
    @ResponseWrapper(localName = "queryPromNameResponse", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.QueryPromNameResponse")
    public String queryPromName(
            @WebParam(name = "itemNo", targetNamespace = "")
                    String itemNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRtnRight", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.GetRtnRight")
    @WebMethod
    @ResponseWrapper(localName = "getRtnRightResponse", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.GetRtnRightResponse")
    public String getRtnRight(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "preSale", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.PreSale")
    @WebMethod
    @ResponseWrapper(localName = "preSaleResponse", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.PreSaleResponse")
    public String preSale(
            @WebParam(name = "saleInfo", targetNamespace = "")
                    String saleInfo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "makeJffl", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.MakeJffl")
    @WebMethod
    @ResponseWrapper(localName = "makeJfflResponse", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.MakeJfflResponse")
    public String makeJffl(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    double arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    double arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    double arg5
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sale", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.Sale")
    @WebMethod
    @ResponseWrapper(localName = "saleResponse", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.SaleResponse")
    public String sale(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "couponQuery", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.CouponQuery")
    @WebMethod
    @ResponseWrapper(localName = "couponQueryResponse", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.CouponQueryResponse")
    public String couponQuery(
            @WebParam(name = "couponNo", targetNamespace = "")
                    String couponNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "czkQuery", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.CzkQuery")
    @WebMethod
    @ResponseWrapper(localName = "czkQueryResponse", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.CzkQueryResponse")
    public String czkQuery(
            @WebParam(name = "cdinfo", targetNamespace = "")
                    String cdinfo,
            @WebParam(name = "shopId", targetNamespace = "")
                    String shopId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "makeCoupon", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.MakeCoupon")
    @WebMethod
    @ResponseWrapper(localName = "makeCouponResponse", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.MakeCouponResponse")
    public String makeCoupon(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryJffl", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.QueryJffl")
    @WebMethod
    @ResponseWrapper(localName = "queryJfflResponse", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.QueryJfflResponse")
    public String queryJffl(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "vipQuery", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.VipQuery")
    @WebMethod
    @ResponseWrapper(localName = "vipQueryResponse", targetNamespace = "http://impl.webService.site.com/", className = "com.site.webService.call.VipQueryResponse")
    public String vipQuery(
            @WebParam(name = "cdinfo", targetNamespace = "")
                    String cdinfo,
            @WebParam(name = "billno", targetNamespace = "")
                    String billno,
            @WebParam(name = "shopId", targetNamespace = "")
                    String shopId
    );
}
